excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://jonzfisher.github.io
title: Awesome
email: jonathanzfisher@gmail.com
author: Jonathan Fisher
description: My awesome new site
paginate: 3
google_analytics: 